/* =======================================================
   Curated medicine + interaction dataset.
   Educational subset only — a real deployment would replace
   this with a live source such as RxNorm or the openFDA API.
   ======================================================= */

const MEDICINES = [
  {name:"Dolo", cls:"Paracetamol (Pain & Fever Relief)"},
  {name:"Warfarin", cls:"Anticoagulant"},
  {name:"Aspirin", cls:"NSAID / Antiplatelet"},
  {name:"Ibuprofen", cls:"NSAID"},
  {name:"Diclofenac", cls:"NSAID"},
  {name:"Naproxen", cls:"NSAID"},
  {name:"Clopidogrel", cls:"Antiplatelet"},
  {name:"Omeprazole", cls:"PPI"},
  {name:"Pantoprazole", cls:"PPI"},
  {name:"Metformin", cls:"Antidiabetic (Biguanide)"},
  {name:"Insulin", cls:"Antidiabetic"},
  {name:"Glimepiride", cls:"Antidiabetic (Sulfonylurea)"},
  {name:"Lisinopril", cls:"ACE Inhibitor"},
  {name:"Enalapril", cls:"ACE Inhibitor"},
  {name:"Spironolactone", cls:"Potassium-sparing Diuretic"},
  {name:"Furosemide", cls:"Loop Diuretic"},
  {name:"Digoxin", cls:"Cardiac Glycoside"},
  {name:"Sertraline", cls:"SSRI (Antidepressant)"},
  {name:"Fluoxetine", cls:"SSRI (Antidepressant)"},
  {name:"Escitalopram", cls:"SSRI (Antidepressant)"},
  {name:"Phenelzine", cls:"MAOI (Antidepressant)"},
  {name:"Tramadol", cls:"Opioid Analgesic"},
  {name:"Codeine", cls:"Opioid Analgesic"},
  {name:"Alprazolam", cls:"Benzodiazepine"},
  {name:"Diazepam", cls:"Benzodiazepine"},
  {name:"Sildenafil", cls:"PDE5 Inhibitor"},
  {name:"Nitroglycerin", cls:"Nitrate"},
  {name:"Isosorbide Mononitrate", cls:"Nitrate"},
  {name:"Metronidazole", cls:"Antibiotic"},
  {name:"Ciprofloxacin", cls:"Antibiotic (Fluoroquinolone)"},
  {name:"Clarithromycin", cls:"Antibiotic (Macrolide)"},
  {name:"Azithromycin", cls:"Antibiotic (Macrolide)"},
  {name:"Simvastatin", cls:"Statin"},
  {name:"Atorvastatin", cls:"Statin"},
  {name:"Levothyroxine", cls:"Thyroid Hormone"},
  {name:"Calcium Carbonate", cls:"Mineral Supplement"},
  {name:"Ferrous Sulfate", cls:"Iron Supplement"},
  {name:"Methotrexate", cls:"Antimetabolite (DMARD)"},
  {name:"Lithium", cls:"Mood Stabilizer"},
  {name:"Theophylline", cls:"Bronchodilator"},
  {name:"Amlodipine", cls:"Calcium Channel Blocker"},
  {name:"Losartan", cls:"ARB"},
];

const INTERACTIONS = [
  {a:"warfarin", b:"aspirin", severity:"danger",
    text:"Both reduce the blood's ability to clot, aspirin through platelets and warfarin through clotting factors. Taken together, the bleeding risk stacks rather than staying flat — this combination is a leading cause of hospital admissions for internal bleeding.",
    reco:"Needs direct doctor supervision. Watch for unusual bruising, black stools, or bleeding gums and seek care immediately if they appear."},
  {a:"warfarin", b:"ibuprofen", severity:"danger",
    text:"Ibuprofen irritates the stomach lining and also affects clotting, so on top of warfarin's blood-thinning effect it sharply raises the risk of gastrointestinal bleeding.",
    reco:"Avoid this combination; paracetamol is generally a safer pain-relief alternative for someone on warfarin, but confirm with a doctor first."},
  {a:"warfarin", b:"diclofenac", severity:"danger",
    text:"Same mechanism as with other NSAIDs — diclofenac adds gut and clotting risk on top of warfarin's anticoagulant effect.",
    reco:"Avoid; ask a doctor for a warfarin-safe pain reliever."},
  {a:"warfarin", b:"metronidazole", severity:"danger",
    text:"Metronidazole slows down the liver enzyme that clears warfarin from the body, so warfarin builds up and thins the blood more than intended.",
    reco:"Dose of warfarin often needs to be lowered during metronidazole treatment — this should only be adjusted by a doctor, never self-managed."},
  {a:"clopidogrel", b:"omeprazole", severity:"caution",
    text:"Omeprazole can block the liver enzyme that activates clopidogrel, meaning clopidogrel may not work as well at preventing clots.",
    reco:"Pantoprazole is usually a safer PPI choice alongside clopidogrel — this swap is a common one doctors make."},
  {a:"aspirin", b:"ibuprofen", severity:"caution",
    text:"Ibuprofen can block aspirin's access to the platelet target it needs for its heart-protective effect, and taking them together adds to stomach irritation.",
    reco:"If both are needed, timing matters (aspirin taken well before ibuprofen) — confirm the right spacing with a pharmacist."},
  {a:"lisinopril", b:"spironolactone", severity:"danger",
    text:"Both drugs cause the body to retain potassium. Together, potassium levels can climb high enough to affect heart rhythm.",
    reco:"Requires regular blood potassium monitoring if prescribed together — don't combine without a doctor tracking levels."},
  {a:"enalapril", b:"spironolactone", severity:"danger",
    text:"Same potassium-retention mechanism as lisinopril + spironolactone — the combination can push potassium to dangerous levels.",
    reco:"Needs monitored potassium levels; not for unsupervised use."},
  {a:"digoxin", b:"furosemide", severity:"caution",
    text:"Furosemide can lower potassium levels, and low potassium makes the heart more sensitive to digoxin — increasing the chance of digoxin toxicity even at a normal dose.",
    reco:"Potassium levels should be checked periodically; report nausea, confusion, or visual changes to a doctor promptly."},
  {a:"sertraline", b:"tramadol", severity:"danger",
    text:"Both raise serotonin activity in the brain. Combined, they can trigger serotonin syndrome — agitation, rapid heart rate, high fever, and in severe cases it's life-threatening.",
    reco:"Avoid combining without specialist advice; seek urgent care for confusion, muscle twitching, or high fever."},
  {a:"fluoxetine", b:"tramadol", severity:"danger",
    text:"Same serotonin-stacking risk as sertraline + tramadol.",
    reco:"Avoid without specialist advice."},
  {a:"escitalopram", b:"tramadol", severity:"danger",
    text:"Same serotonin-stacking risk as other SSRIs combined with tramadol.",
    reco:"Avoid without specialist advice."},
  {a:"phenelzine", b:"sertraline", severity:"danger",
    text:"MAOIs and SSRIs both increase serotonin through different pathways; combined, the risk of serotonin syndrome is severe and well-documented.",
    reco:"These should never be combined; a washout period of at least two weeks is typically required when switching between them, under medical supervision."},
  {a:"alprazolam", b:"tramadol", severity:"danger",
    text:"Both suppress the central nervous system. Together they can slow breathing to a dangerous degree, especially in older adults.",
    reco:"Avoid combining; if both are medically necessary, this needs close doctor supervision."},
  {a:"diazepam", b:"codeine", severity:"danger",
    text:"Combining a benzodiazepine with an opioid compounds sedation and breathing suppression — a combination linked to a large share of overdose deaths.",
    reco:"Avoid combining; flag this to a prescriber if both appear on a prescription."},
  {a:"sildenafil", b:"nitroglycerin", severity:"danger",
    text:"Both drugs widen blood vessels. Together they can cause blood pressure to fall suddenly and severely, which can be life-threatening.",
    reco:"Never combine these. This is one of the most well-known absolute contraindications in cardiology."},
  {a:"sildenafil", b:"isosorbide mononitrate", severity:"danger",
    text:"Same blood-pressure-crash risk as sildenafil + nitroglycerin.",
    reco:"Never combine these."},
  {a:"ciprofloxacin", b:"theophylline", severity:"caution",
    text:"Ciprofloxacin slows the breakdown of theophylline, letting it build up to levels that can cause nausea, tremors, or seizures.",
    reco:"Theophylline levels should be monitored if the two are prescribed together."},
  {a:"simvastatin", b:"clarithromycin", severity:"danger",
    text:"Clarithromycin blocks the liver enzyme that clears simvastatin, letting it build up to levels that raise the risk of severe muscle breakdown (rhabdomyolysis).",
    reco:"This combination is usually avoided outright; a doctor would typically pause the statin during antibiotic treatment."},
  {a:"atorvastatin", b:"clarithromycin", severity:"caution",
    text:"Similar enzyme-blocking effect as with simvastatin, though atorvastatin is affected somewhat less severely.",
    reco:"Still worth flagging to a doctor — a lower statin dose or temporary pause is common during treatment."},
  {a:"levothyroxine", b:"calcium carbonate", severity:"caution",
    text:"Calcium binds to levothyroxine in the gut and reduces how much of it gets absorbed, which can undertreat an underactive thyroid.",
    reco:"Space the two doses at least 4 hours apart rather than avoiding either medicine."},
  {a:"levothyroxine", b:"ferrous sulfate", severity:"caution",
    text:"Iron binds levothyroxine in the gut the same way calcium does, lowering its absorption.",
    reco:"Space doses at least 4 hours apart."},
  {a:"methotrexate", b:"ibuprofen", severity:"danger",
    text:"NSAIDs can reduce how the kidneys clear methotrexate, letting it accumulate to toxic levels that affect bone marrow and the liver.",
    reco:"This combination needs explicit doctor sign-off, especially at higher methotrexate doses used for cancer or severe autoimmune disease."},
  {a:"methotrexate", b:"naproxen", severity:"danger",
    text:"Same kidney-clearance interference as methotrexate + ibuprofen.",
    reco:"Needs explicit doctor sign-off."},
  {a:"lithium", b:"ibuprofen", severity:"danger",
    text:"NSAIDs reduce kidney clearance of lithium, which has a narrow safety margin — levels can rise into the toxic range.",
    reco:"Avoid NSAIDs on lithium where possible; paracetamol is the usual safer alternative."},
  {a:"lithium", b:"furosemide", severity:"danger",
    text:"Diuretics change sodium balance in a way that causes the kidneys to reabsorb more lithium, pushing levels toward toxicity.",
    reco:"Requires monitored lithium blood levels if combined."},
  {a:"metformin", b:"furosemide", severity:"caution",
    text:"Diuretics can affect kidney function, and metformin depends on healthy kidneys to be cleared safely — impaired clearance raises the risk of a rare but serious complication (lactic acidosis).",
    reco:"Kidney function should be checked periodically for anyone on both."},
];
